version: "3.1"

services:
  db-oracle:
    image: oracle/database:19.3.0-ee
    restart: unless-stopped
    ports:
      - 1521:1521
      - 5500:5500
      # - 8080:8080
    environment:
      ORACLE_PW: oracle
      # esquema do despejo que você deseja importar
      SOURCE_SCHEMA: change-or-delete-me
      # espaço de tabela do despejo que você deseja importar
      SOURCE_TABLESPACE: change-or-delete-me
      # você pode querer excluir `GRANT`:` EXCLUDE = USER, GRANT ', se seu dump os contiver
      # se você não tem nada a excluir, remova a variável
      EXCLUDE: user
    volumes:
      - ./volumes/oracle/data:/opt/oracle/oradata
